### ISSUE TITLE
Enhancement: Convert between orders

### ISSUE THREAD

**Issue by RosaryMala** [bpoxy/plex-tvdb-alt-orderer#10]
Suppose I have a series currently in DVD order (Because that what Plex is able to support) and I want to change a show to instead be in, say, Book order. Would it be possible to add that option to the script or would that require renaming files?

**Comment by bpoxy** [comment]
This tool was created simply to populate Plex metadata for an ordering that is already present on the file system. It will be made obsolete when Plex starts supporting orders other than aired and DVD. 

The conversion you are asking for indeed requires renaming files, which I don't believe this tool should do as A) it is pretty easy to screw up, B) it is relatively irreversible, and C) naming conventions vary.
