### ISSUE TITLE
App will not use regional order for Pokémon anime series

### ISSUE THREAD

**Issue by ethdmill** [bpoxy/plex-tvdb-alt-orderer#5]
App will recognize the series properly, as well as its number of seasons, but throws an error about a missing episode when attempting to use regional order. Confirmed that episode exists in both TVDB regional order and in my filesystem. Specific episode it gets angry about is s10e38. Seems like this might be thrown to mask a different error, but not positive.

**Comment by ethdmill** [comment]
CLI output in attached image. In case the text is a bit iffy, it says: "S10E38 doesn't exist in the selected TVDB order.".

![Capture](https://github.com/bpoxy/plex-tvdb-alt-orderer/assets/25671902/d88a5ffc-f3eb-46df-8248-948bd399087a)

Also attached is a screenshot of the filesystem indicating s10e38 exists. Note: the accent mark over the E is confirmed to not make a difference here, as far as I can tell.

![Capture](https://github.com/bpoxy/plex-tvdb-alt-orderer/assets/25671902/623530ac-2096-40ef-85d5-2653d1ea8453)

**Comment by bpoxy** [comment]
I'm not seeing "Regional Order" on https://thetvdb.com/series/pokemon#seasons. Am I looking at the wrong show?

**Comment by bpoxy** [comment]
Fixed in v0.2.4.
