### ISSUE TITLE
[Feature Request] Rename seasons using alternate order titles

### ISSUE THREAD

**Issue by kvalle22** [bpoxy/plex-tvdb-alt-orderer#6]
Quick question is it possible to rename the seasons using the alternate order titles ? for example for Dragon Ball season 09 would be ' [Season 9 - Piccolo Jr. Saga](https://thetvdb.com/series/dragon-ball/seasons/alternate/9) ' 
![image](https://github.com/bpoxy/plex-tvdb-alt-orderer/assets/26128231/6aad8843-a73c-4af5-862e-29c1a880a837)

**Comment by bpoxy** [comment]
Implemented in v0.3.0.

**Comment by kvalle22** [comment]
### A S T O N I S H I N G
