### ISSUE TITLE
[Feature Request] Fill empty summaries

### ISSUE THREAD

**Issue by kvalle22** [bpoxy/plex-tvdb-alt-orderer#7]
Also fill the empty summaries for each season if the summary is available. 
![image](https://github.com/bpoxy/plex-tvdb-alt-orderer/assets/26128231/c5ccda53-5405-44c9-9c23-4374d6f4f217)
![image](https://github.com/bpoxy/plex-tvdb-alt-orderer/assets/26128231/e62319cc-51dc-4fe7-af25-9280ea2a3d70)

**Comment by bpoxy** [comment]
Implemented in v0.3.0.
